### ISSUE TITLE
api.github.com 可用ip能加上吗？

### ISSUE THREAD

**Issue by lukemin** [wjz304/hosts#2]
api.github.com 可用ip能加上吗？

**Comment by wjz304** [comment]
![image](https://github.com/user-attachments/assets/e578e677-d316-42d8-97aa-61a993e97931)

**Comment by lukemin** [comment]
140.82.121.6不能用，我得到的20.205.243.168可以

**Comment by wjz304** [comment]
好了

**Comment by wjz304** [comment]
阿里云 DNS好像有问题，默认OpenDNS 了，改用 Sunrise 了

**Comment by lukemin** [comment]
感谢
